# Generated by Django 3.1 on 2021-05-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.code')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('aid_message', models.CharField(max_length=150)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_fk', to='server.codelocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location')),
                ('nextCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextcode_fk', to='server.codelocation')),
            ],
        ),
        migrations.AddField(
            model_name='codelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location'),
        ),
    ]
