# Generated by Django 3.1.7 on 2021-05-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='code',
            new_name='code1',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='nextCode',
            new_name='code2',
        ),
    ]
