# Generated by Django 3.1.7 on 2021-05-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210514_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='location',
        ),
        migrations.AddField(
            model_name='region',
            name='codeLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.codelocation'),
        ),
    ]
